// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheHobbyHub.PL.Data;

#nullable disable

namespace TheHobbyHub.PL.Migrations
{
    [DbContext(typeof(HobbyHubEntities))]
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
    [Migration("20240422013839_CreateDatabase")]
========
    [Migration("20240422232246_CreateDatabase")]
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PostalAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblAddress_Id");

                    b.ToTable("tblAddress", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("321dadb6-83df-4d1f-a3c1-6e21f649c3c2"),
========
                            Id = new Guid("9c0edc25-e670-4197-a249-b2dab8cd83b9"),
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                            City = "Anytown",
                            PostalAddress = "123 Main St",
                            State = "CA",
                            Zip = "12345"
                        },
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("a7a71bf4-abc6-4157-8214-c7f60da7efe8"),
========
                            Id = new Guid("887bb6ce-e468-43e5-8318-3a26aac7d9ae"),
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                            City = "Othertown",
                            PostalAddress = "456 Elm St",
                            State = "NY",
                            Zip = "54321"
                        },
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("14bb617d-da09-4a19-bce8-732737c7f47f"),
========
                            Id = new Guid("e1e825e4-9066-4ae9-8b05-87bcdb935442"),
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                            City = "Somewhere",
                            PostalAddress = "789 Oak St",
                            State = "TX",
                            Zip = "67890"
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblCompany_Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("tblCompany", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("3a2f969a-2594-4b2c-9ce9-4ecb0207538a"),
                            AddressId = new Guid("321dadb6-83df-4d1f-a3c1-6e21f649c3c2"),
                            CompanyName = "Company A",
                            Description = "about company A",
                            UserId = new Guid("62347337-4f60-4237-b7f0-b3e7f2705bad")
                        },
                        new
                        {
                            Id = new Guid("b465f88c-90b2-4487-be43-4522309c577d"),
                            AddressId = new Guid("a7a71bf4-abc6-4157-8214-c7f60da7efe8"),
                            CompanyName = "Company B",
                            Description = "about company B",
                            UserId = new Guid("0f2ce9ae-37c8-4a08-b799-80fdaa4340ea")
                        },
                        new
                        {
                            Id = new Guid("9928ef2b-6218-40fd-86aa-7bb7ade4df93"),
                            AddressId = new Guid("14bb617d-da09-4a19-bce8-732737c7f47f"),
                            CompanyName = "Company C",
                            Description = "about company C",
                            UserId = new Guid("50265275-c62f-4f76-bff7-097f91e2e357")
========
                            Id = new Guid("6af33242-83fe-4afb-b9d4-f5c6ad5349c2"),
                            AddressId = new Guid("9c0edc25-e670-4197-a249-b2dab8cd83b9"),
                            CompanyName = "Company A",
                            Description = "about company A",
                            UserId = new Guid("77ade5fe-f0a6-4743-a5e8-440bf6133583")
                        },
                        new
                        {
                            Id = new Guid("b4d9f1f9-ae2c-4d42-b0d4-7f38fb3b0405"),
                            AddressId = new Guid("887bb6ce-e468-43e5-8318-3a26aac7d9ae"),
                            CompanyName = "Company B",
                            Description = "about company B",
                            UserId = new Guid("c56be05d-664d-48c5-966f-2a99ca56a35b")
                        },
                        new
                        {
                            Id = new Guid("ab4f72a2-d45e-40a0-8ccf-8fa345d225d8"),
                            AddressId = new Guid("e1e825e4-9066-4ae9-8b05-87bcdb935442"),
                            CompanyName = "Company C",
                            Description = "about company C",
                            UserId = new Guid("e271ca5f-cb3e-473b-9235-51ec396d76f2")
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("HobbyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblEvent_Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("tblEvent", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("cb03d266-4047-4eee-8ab5-9beb410a3fdb"),
                            AddressId = new Guid("321dadb6-83df-4d1f-a3c1-6e21f649c3c2"),
                            CompanyId = new Guid("3a2f969a-2594-4b2c-9ce9-4ecb0207538a"),
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event A",
                            HobbyId = new Guid("f9f41267-1692-4eb1-b540-0abcf4068e97"),
                            Image = "imageA.jpg",
                            UserId = new Guid("62347337-4f60-4237-b7f0-b3e7f2705bad")
                        },
                        new
                        {
                            Id = new Guid("a4fae146-df60-4620-a8a2-0b774372a9d9"),
                            AddressId = new Guid("a7a71bf4-abc6-4157-8214-c7f60da7efe8"),
                            CompanyId = new Guid("b465f88c-90b2-4487-be43-4522309c577d"),
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event B",
                            HobbyId = new Guid("e52ca2f5-1c02-41e2-8b07-cf9d94421a6c"),
                            Image = "imageB.jpg",
                            UserId = new Guid("0f2ce9ae-37c8-4a08-b799-80fdaa4340ea")
                        },
                        new
                        {
                            Id = new Guid("ad09f6b0-4162-44d9-bc24-76c768f15132"),
                            AddressId = new Guid("14bb617d-da09-4a19-bce8-732737c7f47f"),
                            CompanyId = new Guid("9928ef2b-6218-40fd-86aa-7bb7ade4df93"),
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event C",
                            HobbyId = new Guid("205e81e6-f972-4e54-92ae-2d3cec25e7d8"),
                            Image = "imageC.jpg",
                            UserId = new Guid("50265275-c62f-4f76-bff7-097f91e2e357")
========
                            Id = new Guid("b91295f5-79cd-4fa8-b396-e3275bf46c7b"),
                            AddressId = new Guid("9c0edc25-e670-4197-a249-b2dab8cd83b9"),
                            CompanyId = new Guid("6af33242-83fe-4afb-b9d4-f5c6ad5349c2"),
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event A",
                            HobbyId = new Guid("badebd1f-3d38-4413-a952-cfc7d3a9e12b"),
                            Image = "gym.jpg",
                            UserId = new Guid("77ade5fe-f0a6-4743-a5e8-440bf6133583")
                        },
                        new
                        {
                            Id = new Guid("1d7a3909-8041-4309-b67a-d3ea36d8cddf"),
                            AddressId = new Guid("887bb6ce-e468-43e5-8318-3a26aac7d9ae"),
                            CompanyId = new Guid("b4d9f1f9-ae2c-4d42-b0d4-7f38fb3b0405"),
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event B",
                            HobbyId = new Guid("39ec6c51-867a-4267-a1dd-00b8b0d13651"),
                            Image = "golf.jpg",
                            UserId = new Guid("c56be05d-664d-48c5-966f-2a99ca56a35b")
                        },
                        new
                        {
                            Id = new Guid("13cd03e5-22c8-473c-83ae-2a0f8db5bc6b"),
                            AddressId = new Guid("e1e825e4-9066-4ae9-8b05-87bcdb935442"),
                            CompanyId = new Guid("ab4f72a2-d45e-40a0-8ccf-8fa345d225d8"),
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event C",
                            HobbyId = new Guid("9fabdf5a-50ac-44ca-98ab-cda066e16706"),
                            Image = "running.jpg",
                            UserId = new Guid("e271ca5f-cb3e-473b-9235-51ec396d76f2")
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblFriend", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblFriend_Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("tblFriend", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("a0abf85e-e492-45cb-bd2d-5eaa9a5e6acb"),
                            CompanyId = new Guid("3a2f969a-2594-4b2c-9ce9-4ecb0207538a"),
                            UserId = new Guid("62347337-4f60-4237-b7f0-b3e7f2705bad")
                        },
                        new
                        {
                            Id = new Guid("11918876-1f7e-473a-95e9-7715a4444cf5"),
                            CompanyId = new Guid("b465f88c-90b2-4487-be43-4522309c577d"),
                            UserId = new Guid("0f2ce9ae-37c8-4a08-b799-80fdaa4340ea")
                        },
                        new
                        {
                            Id = new Guid("42ee7aa4-2b0c-4522-a96d-dcedb9eb5b00"),
                            CompanyId = new Guid("9928ef2b-6218-40fd-86aa-7bb7ade4df93"),
                            UserId = new Guid("50265275-c62f-4f76-bff7-097f91e2e357")
========
                            Id = new Guid("0a94383b-d962-4767-867c-129f96fa70ac"),
                            CompanyId = new Guid("6af33242-83fe-4afb-b9d4-f5c6ad5349c2"),
                            UserId = new Guid("77ade5fe-f0a6-4743-a5e8-440bf6133583")
                        },
                        new
                        {
                            Id = new Guid("2f876157-553f-4382-a417-75d67b5fe9ab"),
                            CompanyId = new Guid("b4d9f1f9-ae2c-4d42-b0d4-7f38fb3b0405"),
                            UserId = new Guid("c56be05d-664d-48c5-966f-2a99ca56a35b")
                        },
                        new
                        {
                            Id = new Guid("bc767df3-3fa6-405d-a7ec-5e0197f86107"),
                            CompanyId = new Guid("ab4f72a2-d45e-40a0-8ccf-8fa345d225d8"),
                            UserId = new Guid("e271ca5f-cb3e-473b-9235-51ec396d76f2")
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblHobby", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HobbyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblHobby_Id");

                    b.ToTable("tblHobby", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("f9f41267-1692-4eb1-b540-0abcf4068e97"),
========
                            Id = new Guid("badebd1f-3d38-4413-a952-cfc7d3a9e12b"),
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                            Description = "Gyyymm",
                            HobbyName = "Gym",
                            Type = "Indoor"
                        },
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("e52ca2f5-1c02-41e2-8b07-cf9d94421a6c"),
========
                            Id = new Guid("39ec6c51-867a-4267-a1dd-00b8b0d13651"),
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                            Description = "stick",
                            HobbyName = "Golf",
                            Type = "outdoor"
                        },
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("205e81e6-f972-4e54-92ae-2d3cec25e7d8"),
========
                            Id = new Guid("9fabdf5a-50ac-44ca-98ab-cda066e16706"),
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                            Description = "Run",
                            HobbyName = "Running",
                            Type = "Outdoor"
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("62347337-4f60-4237-b7f0-b3e7f2705bad"),
========
                            Id = new Guid("77ade5fe-f0a6-4743-a5e8-440bf6133583"),
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                            Email = "Alexr@gmail.com",
                            FirstName = "Alex",
                            Image = "image.jpg",
                            LastName = "Rosas",
                            Password = "qUqP5cyxm6YcTAhz05Hph5gvu9M=",
                            PhoneNumber = "2627459097",
                            UserName = "Arosas"
                        },
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("0f2ce9ae-37c8-4a08-b799-80fdaa4340ea"),
========
                            Id = new Guid("c56be05d-664d-48c5-966f-2a99ca56a35b"),
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                            Email = "bfoote@fvtc.edu",
                            FirstName = "Brian",
                            Image = "image.jpg",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            PhoneNumber = "3333333333",
                            UserName = "bfoote"
                        },
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("50265275-c62f-4f76-bff7-097f91e2e357"),
========
                            Id = new Guid("e271ca5f-cb3e-473b-9235-51ec396d76f2"),
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                            Email = "sf@gmail.com",
                            FirstName = "sam",
                            Image = "sammy.jpg",
                            LastName = "fisher",
                            Password = "qUqP5cyxm6YcTAhz05Hph5gvu9M=",
                            PhoneNumber = "1111111111",
                            UserName = "sammyfish"
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblUserHobby", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HobbyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserHobby_Id");

                    b.HasIndex("HobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserHobby", (string)null);

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:TheHobbyHub.PL/Migrations/20240422013839_CreateDatabase.Designer.cs
                            Id = new Guid("e4abd0b5-34c3-4ef8-8954-25108195bf92"),
                            HobbyId = new Guid("f9f41267-1692-4eb1-b540-0abcf4068e97"),
                            UserId = new Guid("62347337-4f60-4237-b7f0-b3e7f2705bad")
                        },
                        new
                        {
                            Id = new Guid("9f0387be-e811-4721-9536-be05fe373946"),
                            HobbyId = new Guid("e52ca2f5-1c02-41e2-8b07-cf9d94421a6c"),
                            UserId = new Guid("0f2ce9ae-37c8-4a08-b799-80fdaa4340ea")
                        },
                        new
                        {
                            Id = new Guid("00284af5-033c-4b45-a963-0d1454561e5c"),
                            HobbyId = new Guid("205e81e6-f972-4e54-92ae-2d3cec25e7d8"),
                            UserId = new Guid("50265275-c62f-4f76-bff7-097f91e2e357")
========
                            Id = new Guid("31829956-c05e-43c1-9f27-1b53e03c2339"),
                            HobbyId = new Guid("badebd1f-3d38-4413-a952-cfc7d3a9e12b"),
                            UserId = new Guid("77ade5fe-f0a6-4743-a5e8-440bf6133583")
                        },
                        new
                        {
                            Id = new Guid("e1fa0a98-7fac-4ff7-b39b-ab2527bc7862"),
                            HobbyId = new Guid("39ec6c51-867a-4267-a1dd-00b8b0d13651"),
                            UserId = new Guid("c56be05d-664d-48c5-966f-2a99ca56a35b")
                        },
                        new
                        {
                            Id = new Guid("4c35e2d0-b743-422f-a0ca-8202abd9f776"),
                            HobbyId = new Guid("9fabdf5a-50ac-44ca-98ab-cda066e16706"),
                            UserId = new Guid("e271ca5f-cb3e-473b-9235-51ec396d76f2")
>>>>>>>> 69cf93f71805db7154167b0098c81ce7b5eea28b:TheHobbyHub.PL/Migrations/20240422232246_CreateDatabase.Designer.cs
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblCompany", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblAddress", "Address")
                        .WithMany("Companies")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("fk_tblCompany_AddressId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblUser", "User")
                        .WithMany("Companies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblCompany_UserId");

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEvent", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblAddress", "Address")
                        .WithMany("Events")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEvent_AddressId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblCompany", "Company")
                        .WithMany("Events")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEvent_CompanyId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblHobby", "Hobby")
                        .WithMany("Events")
                        .HasForeignKey("HobbyId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEvent_HobbyId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblUser", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEvent_UserId");

                    b.Navigation("Address");

                    b.Navigation("Company");

                    b.Navigation("Hobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblFriend", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblCompany", "Company")
                        .WithMany("Friends")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("fk_tblFriend_CompanyId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblUser", "User")
                        .WithMany("Friends")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblFriend_UserId");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblUserHobby", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblHobby", "Hobby")
                        .WithMany("UserHobbies")
                        .HasForeignKey("HobbyId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserHobby_HobbyId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblUser", "User")
                        .WithMany("UserHobbies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserHobby_UserId");

                    b.Navigation("Hobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblAddress", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblCompany", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Friends");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblHobby", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("UserHobbies");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Events");

                    b.Navigation("Friends");

                    b.Navigation("UserHobbies");
                });
#pragma warning restore 612, 618
        }
    }
}
