// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheHobbyHub.PL.Data;

#nullable disable

namespace TheHobbyHub.PL.Migrations
{
    [DbContext(typeof(HobbyHubEntities))]
    [Migration("20240304225130_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblAddress_Id");

                    b.ToTable("tblAddress", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e4e5d5e-e422-4985-a4fb-10fbdb8398b4"),
                            Address = "123 Main St",
                            City = "Anytown",
                            State = "CA",
                            Zip = "12345"
                        },
                        new
                        {
                            Id = new Guid("c64de842-68da-4595-ba47-b8b14467bb31"),
                            Address = "456 Elm St",
                            City = "Othertown",
                            State = "NY",
                            Zip = "54321"
                        },
                        new
                        {
                            Id = new Guid("0a7a37b3-ae3e-47c5-bf28-1a133cdb8974"),
                            Address = "789 Oak St",
                            City = "Somewhere",
                            State = "TX",
                            Zip = "67890"
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblCompany_Id");

                    b.ToTable("tblCompany", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aeb7f848-bfdd-4070-90ca-846b249455fd"),
                            CompanyName = "Company A",
                            Image = "imageA.jpg",
                            Password = "/BafCUbj3r56CjioX1dcB1ynX20=",
                            UserName = "copanyA"
                        },
                        new
                        {
                            Id = new Guid("2e8e90ff-ade4-4921-bc46-1a3bc2cc4f49"),
                            CompanyName = "Company B",
                            Image = "imageB.jpg",
                            Password = "38Nd3/2M+aip9/TyIzVYXKylmQo=",
                            UserName = "companyB"
                        },
                        new
                        {
                            Id = new Guid("f633150c-0062-4382-8830-3f6623240dd6"),
                            CompanyName = "Company C",
                            Image = "imageC.jpg",
                            Password = "urYijG3X2+D44I400gasYPqLBHw=",
                            UserName = "companyC"
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblCompanyAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblCompanyAddress_Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.ToTable("tblCompanyAddress", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("edd4f65b-f124-4e72-ad36-229ab8a20cc3"),
                            AddressId = new Guid("0e4e5d5e-e422-4985-a4fb-10fbdb8398b4"),
                            CompanyId = new Guid("aeb7f848-bfdd-4070-90ca-846b249455fd")
                        },
                        new
                        {
                            Id = new Guid("36e41895-6274-47fc-9626-7f650460e82e"),
                            AddressId = new Guid("c64de842-68da-4595-ba47-b8b14467bb31"),
                            CompanyId = new Guid("2e8e90ff-ade4-4921-bc46-1a3bc2cc4f49")
                        },
                        new
                        {
                            Id = new Guid("13aa05ca-38c0-4810-ac50-fb37e09cb358"),
                            AddressId = new Guid("0a7a37b3-ae3e-47c5-bf28-1a133cdb8974"),
                            CompanyId = new Guid("f633150c-0062-4382-8830-3f6623240dd6")
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("tblAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblEvent_Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("tblAddressId");

                    b.HasIndex("tblUserId");

                    b.ToTable("tblEvent", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9937f374-ee10-4b22-8c0a-020481d24be9"),
                            CompanyId = new Guid("aeb7f848-bfdd-4070-90ca-846b249455fd"),
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event A",
                            Image = "imageA.jpg"
                        },
                        new
                        {
                            Id = new Guid("74554c45-2284-41da-99b2-a64ae3aeebec"),
                            CompanyId = new Guid("2e8e90ff-ade4-4921-bc46-1a3bc2cc4f49"),
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event B",
                            Image = "imageB.jpg"
                        },
                        new
                        {
                            Id = new Guid("09d7cd7d-a7f2-4640-9848-d28d363fd57f"),
                            CompanyId = new Guid("f633150c-0062-4382-8830-3f6623240dd6"),
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Event C",
                            Image = "imageC.jpg"
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEventAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblEventAddress_Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("EventId");

                    b.ToTable("tblEventAddress", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d28dd06-463f-4473-b819-0dcd877414f8"),
                            AddressId = new Guid("0e4e5d5e-e422-4985-a4fb-10fbdb8398b4"),
                            EventId = new Guid("9937f374-ee10-4b22-8c0a-020481d24be9")
                        },
                        new
                        {
                            Id = new Guid("53fb1c38-e8fa-488b-ad3a-f3aa395b1692"),
                            AddressId = new Guid("c64de842-68da-4595-ba47-b8b14467bb31"),
                            EventId = new Guid("74554c45-2284-41da-99b2-a64ae3aeebec")
                        },
                        new
                        {
                            Id = new Guid("3e4482c3-df77-489c-bffc-802c641fa81f"),
                            AddressId = new Guid("1c48472b-0114-43cf-aef0-db951fb4f6af"),
                            EventId = new Guid("09d7cd7d-a7f2-4640-9848-d28d363fd57f")
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEventHobby", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HobbyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblEventHobby_Id");

                    b.HasIndex("EventId");

                    b.HasIndex("HobbyId");

                    b.ToTable("tblEventHobby", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0eeeeff7-9dc4-473f-aca1-1d634ac36d76"),
                            EventId = new Guid("9937f374-ee10-4b22-8c0a-020481d24be9"),
                            HobbyId = new Guid("7695c1ce-81c1-4076-815a-e089eb0fdccf")
                        },
                        new
                        {
                            Id = new Guid("895432f2-e4fd-469f-b69f-3181a7c48c15"),
                            EventId = new Guid("74554c45-2284-41da-99b2-a64ae3aeebec"),
                            HobbyId = new Guid("f8a8905a-9610-4e55-a262-aeecd6293a0d")
                        },
                        new
                        {
                            Id = new Guid("02c2821e-9d25-4f49-abba-1375bd041737"),
                            EventId = new Guid("09d7cd7d-a7f2-4640-9848-d28d363fd57f"),
                            HobbyId = new Guid("24eb281b-ad92-4eb5-a760-aa10a170e47e")
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEventUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblEventUser_Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("tblEventUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("39d53abd-ab7e-4f59-a3a4-5b8784ec8a04"),
                            EventId = new Guid("9937f374-ee10-4b22-8c0a-020481d24be9"),
                            UserId = new Guid("b0981bfe-8235-4055-88cf-cacb3148a542")
                        },
                        new
                        {
                            Id = new Guid("1ab10869-16af-458d-90bb-8cf696cfc31e"),
                            EventId = new Guid("74554c45-2284-41da-99b2-a64ae3aeebec"),
                            UserId = new Guid("e3c5b54c-53f6-4fcd-a9c0-e52c8b98a8ef")
                        },
                        new
                        {
                            Id = new Guid("8654ab8e-b62a-4700-8758-0183eabb04fc"),
                            EventId = new Guid("09d7cd7d-a7f2-4640-9848-d28d363fd57f"),
                            UserId = new Guid("1c48472b-0114-43cf-aef0-db951fb4f6af")
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblFriend", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblFriend_Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("tblFriend", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30365c17-1743-4e50-9882-fbe3527138d6"),
                            CompanyId = new Guid("aeb7f848-bfdd-4070-90ca-846b249455fd")
                        },
                        new
                        {
                            Id = new Guid("a707cc25-d374-4937-ac2e-2ee73f9b6252"),
                            CompanyId = new Guid("2e8e90ff-ade4-4921-bc46-1a3bc2cc4f49")
                        },
                        new
                        {
                            Id = new Guid("adb1d287-e3a3-44a2-840f-c595b77a65ae"),
                            CompanyId = new Guid("f633150c-0062-4382-8830-3f6623240dd6")
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblFriendUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblFriendUser_Id");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("tblFriendUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("038cee8a-89bc-429a-9d5e-b4c882582d24"),
                            FriendId = new Guid("adb1d287-e3a3-44a2-840f-c595b77a65ae"),
                            UserId = new Guid("b0981bfe-8235-4055-88cf-cacb3148a542")
                        },
                        new
                        {
                            Id = new Guid("7324c9fe-c9d8-4283-bc2e-0eece0e096fe"),
                            FriendId = new Guid("a707cc25-d374-4937-ac2e-2ee73f9b6252"),
                            UserId = new Guid("1c48472b-0114-43cf-aef0-db951fb4f6af")
                        },
                        new
                        {
                            Id = new Guid("dd7a13ba-7cd9-4f74-9075-36e7b302c330"),
                            FriendId = new Guid("a707cc25-d374-4937-ac2e-2ee73f9b6252"),
                            UserId = new Guid("1c48472b-0114-43cf-aef0-db951fb4f6af")
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblHobby", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HobbyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblHobby_Id");

                    b.ToTable("tblHobby", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7695c1ce-81c1-4076-815a-e089eb0fdccf"),
                            Description = "Gyyymm",
                            HobbyName = "Gym",
                            Image = "image.jpg",
                            Type = "Indoor"
                        },
                        new
                        {
                            Id = new Guid("f8a8905a-9610-4e55-a262-aeecd6293a0d"),
                            Description = "stick",
                            HobbyName = "Golf",
                            Image = "outdoor.jpg",
                            Type = "outdoor"
                        },
                        new
                        {
                            Id = new Guid("24eb281b-ad92-4eb5-a760-aa10a170e47e"),
                            Description = "Run",
                            HobbyName = "Running",
                            Image = "run.jpg",
                            Type = "Outdoor"
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0981bfe-8235-4055-88cf-cacb3148a542"),
                            Email = "Alexr@gmail.com",
                            FirstName = "Alex",
                            Image = "image.jpg",
                            LastName = "Rosas",
                            Password = "qUqP5cyxm6YcTAhz05Hph5gvu9M=",
                            PhoneNumber = "2627459097",
                            UserName = "Arosas"
                        },
                        new
                        {
                            Id = new Guid("e3c5b54c-53f6-4fcd-a9c0-e52c8b98a8ef"),
                            Email = "ss@gmail.com",
                            FirstName = "Someone",
                            Image = "image.jpg",
                            LastName = "Somebody",
                            Password = "B/qgP3XrZmyneblY753llJ5gtQ4=",
                            PhoneNumber = "3333333333",
                            UserName = "SSM"
                        },
                        new
                        {
                            Id = new Guid("1c48472b-0114-43cf-aef0-db951fb4f6af"),
                            Email = "sf@gmail.com",
                            FirstName = "sam",
                            Image = "sammy.jpg",
                            LastName = "fisher",
                            Password = "qUqP5cyxm6YcTAhz05Hph5gvu9M=",
                            PhoneNumber = "1111111111",
                            UserName = "sammyfish"
                        },
                        new
                        {
                            Id = new Guid("5add4b11-2ba1-404d-b758-63ef7331fb00"),
                            Email = "sf@gmasdfil.com",
                            FirstName = "sdf",
                            Image = "samddmy.jpg",
                            LastName = "fsdfsdfisher",
                            Password = "mNWYTbueAuANF0c6AxbqynRxnXY=",
                            PhoneNumber = "11211111111",
                            UserName = "sasdfsdfmmyfish"
                        },
                        new
                        {
                            Id = new Guid("7869414d-6c36-45d5-bc20-62a28a90f7f7"),
                            Email = "sf@gmrfffail.com",
                            FirstName = "s bvcvbam",
                            Image = "samrrrrmy.jpg",
                            LastName = "fishcvbcvber",
                            Password = "RmQR+JhVJXAHuebYif5zjxpGa70=",
                            PhoneNumber = "11111111111",
                            UserName = "sasfdsdfmmyfish"
                        },
                        new
                        {
                            Id = new Guid("8ef97c06-cd95-4e1f-92f3-71ef31b18131"),
                            Email = "sf@gdfgeeemail.com",
                            FirstName = "sdfgdfgam",
                            Image = "sammeeey.jpg",
                            LastName = "fidfgdfgsher",
                            Password = "AKjX3OOQvQGmIexgkdxqakGshiw=",
                            PhoneNumber = "11112111111",
                            UserName = "sammdfgdfgyfish"
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblUserHobby", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HobbyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserHobby_Id");

                    b.HasIndex("HobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserHobby", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb2a11bb-9271-4aee-bf40-16e423d53b4a"),
                            HobbyId = new Guid("7695c1ce-81c1-4076-815a-e089eb0fdccf"),
                            UserId = new Guid("b0981bfe-8235-4055-88cf-cacb3148a542")
                        },
                        new
                        {
                            Id = new Guid("5c339149-b386-4946-a993-78dde5741f9d"),
                            HobbyId = new Guid("f8a8905a-9610-4e55-a262-aeecd6293a0d"),
                            UserId = new Guid("e3c5b54c-53f6-4fcd-a9c0-e52c8b98a8ef")
                        },
                        new
                        {
                            Id = new Guid("360590ce-9745-45d2-a048-bced21fca0a4"),
                            HobbyId = new Guid("24eb281b-ad92-4eb5-a760-aa10a170e47e"),
                            UserId = new Guid("1c48472b-0114-43cf-aef0-db951fb4f6af")
                        });
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblCompanyAddress", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblAddress", "Address")
                        .WithMany("CompanyAddress")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("fk_tblCompanyAddress_AddressId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblCompany", "Company")
                        .WithMany("CompanyAddress")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("fk_tblCompanyAddress_CompanyId");

                    b.Navigation("Address");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEvent", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblCompany", "Company")
                        .WithMany("Events")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEvent_CompanyId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblAddress", null)
                        .WithMany("Events")
                        .HasForeignKey("tblAddressId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblUser", null)
                        .WithMany("Events")
                        .HasForeignKey("tblUserId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEventAddress", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblAddress", "Addresses")
                        .WithMany("EventAddresses")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEventAddress_AddressId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblEvent", "Events")
                        .WithMany("EventAddresses")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEventAddress_EventId");

                    b.Navigation("Addresses");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEventHobby", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblEvent", "Events")
                        .WithMany("EventHobbies")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEventHobby_EventId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblHobby", "Hobbies")
                        .WithMany("EventHobbies")
                        .HasForeignKey("HobbyId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEventHobby_HobbyId");

                    b.Navigation("Events");

                    b.Navigation("Hobbies");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEventUser", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblEvent", "Events")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEventUser_EventId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblUser", "Users")
                        .WithMany("EventUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblEventUser_UserId");

                    b.Navigation("Events");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblFriend", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblCompany", "Company")
                        .WithMany("Friends")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("fk_tblFriend_CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblFriendUser", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblFriend", "Friend")
                        .WithMany("FriendUsers")
                        .HasForeignKey("FriendId")
                        .IsRequired()
                        .HasConstraintName("fk_tblFriendUser_FriendId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblUser", "User")
                        .WithMany("FriendUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblFriendUser_UserId");

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblUserHobby", b =>
                {
                    b.HasOne("TheHobbyHub.PL.Entities.tblHobby", "Hobby")
                        .WithMany("UserHobbies")
                        .HasForeignKey("HobbyId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserHobby_HobbyId");

                    b.HasOne("TheHobbyHub.PL.Entities.tblUser", "User")
                        .WithMany("UserHobbies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserHobby_UserId");

                    b.Navigation("Hobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblAddress", b =>
                {
                    b.Navigation("CompanyAddress");

                    b.Navigation("EventAddresses");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblCompany", b =>
                {
                    b.Navigation("CompanyAddress");

                    b.Navigation("Events");

                    b.Navigation("Friends");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblEvent", b =>
                {
                    b.Navigation("EventAddresses");

                    b.Navigation("EventHobbies");

                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblFriend", b =>
                {
                    b.Navigation("FriendUsers");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblHobby", b =>
                {
                    b.Navigation("EventHobbies");

                    b.Navigation("UserHobbies");
                });

            modelBuilder.Entity("TheHobbyHub.PL.Entities.tblUser", b =>
                {
                    b.Navigation("EventUsers");

                    b.Navigation("Events");

                    b.Navigation("FriendUsers");

                    b.Navigation("UserHobbies");
                });
#pragma warning restore 612, 618
        }
    }
}
