CREATE TABLE [dbo].[tblEvent]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[AddressId] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[CompanyId] UNIQUEIDENTIFIER NOT NULL,
	[HobbyId] UNIQUEIDENTIFIER NOT NULL,
    [Description] Varchar(MAX) NOT NULL, 
    [Image] Varchar(MAX) NOT NULL, 
	[Date] DATETIME NOT NULL, 

)
